"""Pipeline orchestration (DESIGN.md 3.11).

Three layers, deliberately separate:

* :mod:`~vulnpriority.pipeline.stages` - pure functions, one per step, taking explicit inputs
  and the configuration and returning artifacts. They know nothing about disk or run ids,
  which is what lets the ablation drive eight component cells through the same code.
* :mod:`~vulnpriority.pipeline.artifacts` - the typed on-disk form of what a run produces,
  saved with ``model_dump(mode="json")`` and reloaded through ``model_validate``.
* :mod:`~vulnpriority.pipeline.runner` - order, resumption and the :class:`RunManifest` that
  makes a result reproducible by someone who was not in the room (Gap 4).

Importing this package pulls in no optional dependency and reaches no network: the modules
written by other groups are imported inside the stage that needs them.
"""

from __future__ import annotations

from vulnpriority.pipeline.artifacts import (
    ARTIFACT_FILES,
    RunArtifacts,
    artifact_path,
    default_run_id,
    default_run_root,
    flags_from_columns,
    load_chain,
    load_enriched,
    load_features,
    load_manifest,
    load_metrics,
    load_ranking,
    load_scans,
    load_simulation_capacity,
    new_run_id,
    save_chain,
    save_enriched,
    save_features,
    save_manifest,
    save_metrics,
    save_ranking,
    save_scans,
)
from vulnpriority.pipeline.runner import (
    STAGE_DEPENDENCIES,
    STAGE_ORDER,
    TRACKED_PACKAGES,
    PipelineRunner,
    build_manifest,
    package_versions,
    stage_closure,
)
from vulnpriority.pipeline.stages import (
    ScanAssessment,
    StageUnavailableError,
    ablate_stage,
    adversarial_stage,
    assess_stage,
    attacker_for,
    build_ranker,
    build_simulator,
    capacity_from_payload,
    capacity_payload,
    chain_stage,
    enrich_stage,
    evaluate_stage,
    feature_stage,
    impact_model_for,
    ingest_stage,
    intel_by_cve,
    label_stage,
    policy_rankings,
    rank_stage,
    report_stage,
    resolve_as_of,
    select_stage,
    selection_policies,
    selection_table,
    simulate_stage,
    split_stage,
)

__all__ = [
    "ARTIFACT_FILES",
    "STAGE_DEPENDENCIES",
    "STAGE_ORDER",
    "TRACKED_PACKAGES",
    "PipelineRunner",
    "RunArtifacts",
    "ScanAssessment",
    "StageUnavailableError",
    "ablate_stage",
    "adversarial_stage",
    "artifact_path",
    "assess_stage",
    "attacker_for",
    "build_manifest",
    "build_ranker",
    "build_simulator",
    "capacity_from_payload",
    "capacity_payload",
    "chain_stage",
    "default_run_id",
    "default_run_root",
    "enrich_stage",
    "evaluate_stage",
    "feature_stage",
    "flags_from_columns",
    "impact_model_for",
    "ingest_stage",
    "intel_by_cve",
    "label_stage",
    "load_chain",
    "load_enriched",
    "load_features",
    "load_manifest",
    "load_metrics",
    "load_ranking",
    "load_scans",
    "load_simulation_capacity",
    "new_run_id",
    "package_versions",
    "policy_rankings",
    "rank_stage",
    "report_stage",
    "resolve_as_of",
    "save_chain",
    "save_enriched",
    "save_features",
    "save_manifest",
    "save_metrics",
    "save_ranking",
    "save_scans",
    "select_stage",
    "selection_policies",
    "selection_table",
    "simulate_stage",
    "split_stage",
    "stage_closure",
]
